## array数组转换成其它数据类型

In [1]:
import numpy as np

### 将数组转换成列表
- ndarray.tolist()
- list(ndarray)

#### 一维数组

In [2]:
data = np.arange(20)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
type(data)

numpy.ndarray

In [3]:
list_data = data.tolist()
list_data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [4]:
type(list_data)

list

In [8]:
list_data2 = list(data)
list_data2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [9]:
type(list_data2)

list

#### 二维数组

In [10]:
data = np.arange(20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
type(data)

numpy.ndarray

In [12]:
list_data = data.tolist()
list_data

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

In [13]:
type(list_data)

list

In [14]:
list_data2 = list(data)
list_data2

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [15]:
type(list_data2)

list

#### 三维数组

In [16]:
data = np.arange(20).reshape(2,2,5)
data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [17]:
type(data)

numpy.ndarray

In [18]:
list_data = data.tolist()
list_data

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]],
 [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]]

In [19]:
type(list_data)

list

In [20]:
list_data2 = list(data)
list_data2

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [21]:
type(list_data2)

list

#### 注意：
1. 使用ndarray.tolist()会将数组完整的转换成列表
2. 使用python自带的list()方法，只会将第一层转换成列表
    - 也就是当数组是一维数组时，使用ndarray.tolist()和list()效果相同
    - 当数组是多维数组时
        - ndarray.tolist()能够正常的将数组全部转换成列表，列表里的元素仍然是列表
        - 而list()函数只会将数组转换成列表，但是列表里的元素还是数组类型

### 将数组转换成字符串
- ndarray.tostring()  已经弃用，建议使用ndarray.tobytes()
- str(ndarray)
- ndarray.tobytes()

#### 一维数组

In [28]:
data = np.arange(20)
display(data,type(data))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

numpy.ndarray

In [23]:
str_data = data.tostring()
display(str_data,type(str_data))

C:\Users\86136\AppData\Local\Temp\ipykernel_58616\758029222.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  str_data = data.tostring()


b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00'

bytes

In [24]:
str_data = data.tobytes()
display(str_data,type(str_data))

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00'

bytes

In [29]:
str_data = str(data)
display(str_data,type(str_data))

'[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]'

str

#### 二维数组

In [31]:
data = np.arange(20).reshape(4,5)
display(data, type(data))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

numpy.ndarray

In [32]:
str_data = data.tobytes()
display(str_data,type(str_data))

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00'

bytes

In [33]:
str_data = str(data)
display(str_data,type(str_data))

'[[ 0  1  2  3  4]\n [ 5  6  7  8  9]\n [10 11 12 13 14]\n [15 16 17 18 19]]'

str

#### 三维数组

In [34]:
data = np.arange(20).reshape(2,2,5)
display(data, type(data))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

numpy.ndarray

In [35]:
str_data = data.tobytes()
display(str_data,type(str_data))

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00'

bytes

In [36]:
str_data = str(data)
display(str_data,type(str_data))

'[[[ 0  1  2  3  4]\n  [ 5  6  7  8  9]]\n\n [[10 11 12 13 14]\n  [15 16 17 18 19]]]'

str

### 将数组写入文件保存
- ndarray.tofile(fid, sep=" ", format='%s')
    - fid：文件名
    - sep：元素分隔符 当sep=""空时，则向文件写入二进制
    - format：格式化默认 %s

#### 一维数组

In [37]:
data = np.arange(20)
display(data,type(data))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

numpy.ndarray

In [39]:
data.tofile("1-dim-array.txt", sep=" ", format='%s')

#### 二维数组

In [42]:
data = np.arange(20).reshape(4,5)
display(data, type(data))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

numpy.ndarray

In [43]:
data.tofile("2-dim-array.txt", sep=" ")

#### 三维数组

In [44]:
data = np.arange(20).reshape(2,2,5)
display(data, type(data))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

numpy.ndarray

In [45]:
data.tofile("3-dim-array.txt", sep=",", format='%s')

### 无论数组的维度，最后存入文件的都是一个个元素，相当于遍历数组，然后存入文件

### numpy也提供了一系列save文件和读取文件的方法，这里以存储txt和读取txt文件为例

- 将数组存储为txt文件
    - np.savetxt(filename,ndarray)
- 将txt文件读取成数组
    - np.laodtxt(filename)

#### 一维数组

In [47]:
data = np.arange(20)
display(data,type(data))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

numpy.ndarray

In [50]:
np.savetxt("np-1-dim-array.txt", data)

In [54]:
np.loadtxt("np-1-dim-array.txt")

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

#### 二维数组

In [55]:
data = np.arange(20).reshape(4,5)
display(data, type(data))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

numpy.ndarray

In [56]:
np.savetxt("np-2-dim-array.txt", data)

In [57]:
np.loadtxt("np-2-dim-array.txt")

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

#### 三维数组

In [58]:
data = np.arange(20).reshape(2,2,5)
display(data, type(data))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

numpy.ndarray

In [59]:
np.savetxt("np-3-dim-array.txt", data)

ValueError: Expected 1D or 2D array, got 3D array instead

- np.savetxt(filename,ndarray) 会将数组按照数组原样存储到txt文件里，并且是以科学计数法的形式存储，另外此函数只支持一维数组和二维数组
- np.loadtxt(filename) 会将txt文本读取成数组，默认读取成np.float64类型
- 另外使用numpy读取和存储文件，实际使用时很少，会使用之后学习的pandas进行存储和读取

### 将数组里的元素类型进行转换
- 使用ndarray.astype()

In [60]:
data = np.array([1,2,3,4,5], dtype=np.int8)
display(data,data.dtype)

array([1, 2, 3, 4, 5], dtype=int8)

dtype('int8')

In [62]:
new_data = data.astype(np.int16)
new_data.dtype

dtype('int16')

In [63]:
new_data = data.astype(np.int64)
new_data.dtype

dtype('int64')

In [64]:
new_data = data.astype(np.float32)
new_data.dtype

dtype('float32')

> ndarray.astype()会生成新的数组，而不是修改原本数组的数据类型

## 注意：
- 在之前或者之后的讲解中，有的函数会生成新的数组，修改新的数组不会影响原先数组
- 而有的函数只会生成原数组的视图，如果修改这个视图，那么原本的数组也会被修改
- 在实际运用是时，只需要特地修改一下查看原本数组是否会改变就可，不用专门记忆哪些函数会生成新的数组，哪些函数是生成视图