## numpy数组形状变换

In [1]:
import numpy as np

1. reshape()方法
2. resize()方法
3. ndarray的shape属性
4. ravel()方法
5. flaten()方法
6. 转置
    - 6.1 使用ndarray的T属性
    - 6.2 使用numpy的transpose(ndarray)方法

- reshape()返回新的数组的视图
    - 修改reshape后的数组的值会影响原先数组的值

In [3]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
new_data = data.reshape(2,5)
new_data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
new_data[0,0] = 100
display(new_data, data)

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

- resize() 直接修改原本数组形状，无返回值

In [6]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
data.resize(5,2)
data

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

- 直接给数组shape属性赋值也可以修改原本数据的形状

In [9]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
data.shape=(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

- ravel() 将高维数组展开为一维数组,会生成新的数组，是原先数组的视图

In [11]:
data = np.arange(10).reshape(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
new_data = data.ravel()
new_data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
new_data[0] = 100
display(new_data, data)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [14]:
data = np.arange(20).reshape(2,2,5)
data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [15]:
new_data = data.ravel()
new_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

- flatten() 将高维数组展开为一维数组，生成新的数组的副本，修改新的数组不影响原先数组

In [16]:
data = np.arange(10).reshape(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
new_data = data.flatten()
new_data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
new_data[0] = 100
display(new_data, data)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
data = np.arange(20).reshape(2,2,5)
data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [20]:
new_data = data.flatten()
new_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
new_data[0] = 100
display(new_data, data)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

### 补充知识
- 一维数组只有列，shape过后是一个一个元素的元组，默认一维数组的轴为0轴
- 二维数组，有行有列，shape过后是(行,列)，则二维数组的行是0轴，二维数组的列是1轴
- 三维数组，不妨shape过后设为(页,行,列),则页为0轴，行为1轴，列为2轴
- 注意：在二维空间，行轴从左到右，列轴从上往下为正方向

> 数组的转置，一般用于二维数组

- 数组的属性T和numpy的transpose()都是将二维数组进行转置，也就是行变成列，列变成行
- 这两种方法生成的新数组都是原数组的视图

In [28]:
data = np.arange(10).reshape(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
new_data = data.T
new_data

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [30]:
new_data[0,0] = 100
display(new_data, data)

array([[100,   5],
       [  1,   6],
       [  2,   7],
       [  3,   8],
       [  4,   9]])

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [31]:
new_data = np.transpose(data)
new_data

array([[100,   5],
       [  1,   6],
       [  2,   7],
       [  3,   8],
       [  4,   9]])

In [32]:
new_data[0,1]=200
display(new_data, data)

array([[100, 200],
       [  1,   6],
       [  2,   7],
       [  3,   8],
       [  4,   9]])

array([[100,   1,   2,   3,   4],
       [200,   6,   7,   8,   9]])