## numpy数组算术运算

In [1]:
import numpy as np

#### 1. 数组和数字运算 
- 数组和数字运算，是将数字和数组中每个元素进行运算

In [2]:
data1 = np.arange(10)
data2 = np.arange(20).reshape(4,5)
data3 = np.arange(20).reshape(2,2,5)
display(data1,data2,data3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [3]:
display(data1 + 100, data1 - 20, data1 * 10, data1 /10, data1 % 2, data1 // 2, data1**2)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
display(data2 + 100, data2 - 20, data2 * 10, data2 /10, data2 % 2, data2 // 2, data2**2)

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]])

array([[-20, -19, -18, -17, -16],
       [-15, -14, -13, -12, -11],
       [-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1]])

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

array([[0, 0, 1, 1, 2],
       [2, 3, 3, 4, 4],
       [5, 5, 6, 6, 7],
       [7, 8, 8, 9, 9]], dtype=int32)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [5]:
display(data3 + 100, data3 - 20, data3 * 10, data3 /10, data3 % 2, data3 // 2, data3**2)

array([[[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]],

       [[110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]]])

array([[[-20, -19, -18, -17, -16],
        [-15, -14, -13, -12, -11]],

       [[-10,  -9,  -8,  -7,  -6],
        [ -5,  -4,  -3,  -2,  -1]]])

array([[[  0,  10,  20,  30,  40],
        [ 50,  60,  70,  80,  90]],

       [[100, 110, 120, 130, 140],
        [150, 160, 170, 180, 190]]])

array([[[0. , 0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8, 0.9]],

       [[1. , 1.1, 1.2, 1.3, 1.4],
        [1.5, 1.6, 1.7, 1.8, 1.9]]])

array([[[0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1]],

       [[0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1]]], dtype=int32)

array([[[0, 0, 1, 1, 2],
        [2, 3, 3, 4, 4]],

       [[5, 5, 6, 6, 7],
        [7, 8, 8, 9, 9]]], dtype=int32)

array([[[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81]],

       [[100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]]])

##### 补充几个方法
- np.exp指数运算
- np.log对数运算、哪怕。log10
- np.abs绝对值

In [38]:
data = np.arange(1,21).reshape(4,5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [39]:
np.exp(data)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08]])

In [40]:
np.log(data)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227]])

In [41]:
np.log10(data)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ]])

#### 2. 相同维度的两个数组进行运算
- 对应位置对应元素进行运算

In [6]:
data1 = np.arange(10)
data2 = np.arange(10,20)
display(data1,data2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
display(data1+data2, data1-data2, data1*data2, data1/data2, data1%data2,data1//data2,data1**data2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([          0,           1,        4096,     1594323,   268435456,
         452807053,  -683606016, -2094633337,           0,  -400556711])

In [8]:
data1 = np.arange(10).reshape(2,5)
data2 = np.arange(10,20).reshape(2,5)
display(data1,data2)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
display(data1+data2, data1-data2, data1*data2, data1/data2, data1%data2,data1//data2,data1**data2)

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

array([[          0,           1,        4096,     1594323,   268435456],
       [  452807053,  -683606016, -2094633337,           0,  -400556711]])

In [10]:
data1 = np.arange(24).reshape(2,3,4)
data2 = np.arange(24,48).reshape(2,3,4)
display(data1,data2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [11]:
display(data1+data2, data1-data2, data1*data2, data1/data2, data1%data2,data1//data2,data1**data2)

array([[[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]],

       [[48, 50, 52, 54],
        [56, 58, 60, 62],
        [64, 66, 68, 70]]])

array([[[-24, -24, -24, -24],
        [-24, -24, -24, -24],
        [-24, -24, -24, -24]],

       [[-24, -24, -24, -24],
        [-24, -24, -24, -24],
        [-24, -24, -24, -24]]])

array([[[   0,   25,   52,   81],
        [ 112,  145,  180,  217],
        [ 256,  297,  340,  385]],

       [[ 432,  481,  532,  585],
        [ 640,  697,  756,  817],
        [ 880,  945, 1012, 1081]]])

array([[[0.        , 0.04      , 0.07692308, 0.11111111],
        [0.14285714, 0.17241379, 0.2       , 0.22580645],
        [0.25      , 0.27272727, 0.29411765, 0.31428571]],

       [[0.33333333, 0.35135135, 0.36842105, 0.38461538],
        [0.4       , 0.41463415, 0.42857143, 0.44186047],
        [0.45454545, 0.46666667, 0.47826087, 0.4893617 ]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

array([[[          0,           1,    67108864,  2030534587],
        [          0,  1804648021,  1073741824,   265001655],
        [          0,  1165272329,           0,   223731123]],

       [[          0, -1053241123,           0,  1119702383],
        [          0,  -946637167,           0,   764714667],
        [          0,   101251813,           0,  1016499751]]])

#### 3. 不同维度的两个数组进行运算
- 这里不同维度包括两种情况：
    1. 维度个数不同，例如一个一维，一个二维 
    2. 相同维度，但是数据个数不同，例如两个都是二维数组，一个(2,3)，一个(3,2)
- 若符合广播机制，则可以运算，并且运算结果的维度，是两个数组维度高的形状
- 若不符合广播机制，则无法计算

#### 广播机制
- 相同维度，但是数据个数不同：
    - 如果对应维度的个数不同，但是不同的那个维度，元素个数为1，则可以广播
        - 例如：
            1. a = (2,3) b=(2,1) 可以，1轴的元素个数不同，但是b的1轴是1，满足广播机制
            2. a = (2,3) b=(2,4) 不可以，1轴的元素个数不同，且都不为1，不满足广播机制
            3. a = (1,2,3) b=(3,1,3) 可以，0轴和1轴不同，但是存在1，满足广播机制
    - 如果维度不同，但是相对于低维数组，高维数组除去多出的维度，从右往左数，其元素个数不同的维度，为1，则满足广播机制
        - 例如：
            1. a = (1,2,3) b=(2,3) 可以，从右往左看，第一个轴、第二个轴元素个数相同，满足广播机制
            2. a = (3,1,5) b = (1,6) 不可以，从右往左看，第一个轴元素个数不同，且不是1，不满足广播机制
            3. a = (3,1,5) b = (1,5) 可以，从右往左看，第一个轴、第二个轴元素个数相同，满足广播机制
            4. a = (1,2,1,2) b=(2,5,2) 可以，从右往左看，第二个轴元素个数相同，但是值为1，满足广播机制
            - 特别的：
                - a=(1,2,3) b=(3,) 可以，像这样的一维数组，(n,) 当作 (1,n)形状进行广播判断
- 广播计算后的形状：
    - 对应维度的个数不同：
        1. a = (2,3) b=(2,1)   b进行元素复制 => b=(2,3)  计算结果为 (2,3)
        2. a = (1,2,3) b=(3,1,3) a进行元素复制 => a=(3,2,3) b进行元素复制 => b=(3, 2,3) 计算结果为 (3,2,3)
    - 维度不同:
        1. a = (1,2,3) b=(2,3)  b进行元素复制 => b=(1, 2,3) 计算结果为 (1,2,3)
        2. a = (1,2,1,2) b=(2,5,2) a进行元素复制 => a=(1,2,5,2) b进行元素复制 => b=(1,2,5,2) 计算结果为 b=(1,2,5,2)
        3. a=(1,2,3) b=(3,)   b进行元素复制 => b=(1, 2,3)  计算结果为 (1,2,3)

#### 对应维度的个数不同

In [14]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,3).reshape(2,1)
display(a,b)

array([[1, 2, 3],
       [4, 5, 6]])

array([[1],
       [2]])

In [15]:
display(a + b, a - b, a * b, a / b, a%b, a//b, a**b)

array([[2, 3, 4],
       [6, 7, 8]])

array([[0, 1, 2],
       [2, 3, 4]])

array([[ 1,  2,  3],
       [ 8, 10, 12]])

array([[1. , 2. , 3. ],
       [2. , 2.5, 3. ]])

array([[0, 0, 0],
       [0, 1, 0]])

array([[1, 2, 3],
       [2, 2, 3]])

array([[ 1,  2,  3],
       [16, 25, 36]])

In [16]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,9).reshape(2,4)
display(a,b)

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

In [18]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,10).reshape(3,1,3)
display(a,b)

array([[1, 2, 3],
       [4, 5, 6]])

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [19]:
display(a + b, a - b, a * b, a / b, a%b, a//b, a**b)

array([[[ 2,  4,  6],
        [ 5,  7,  9]],

       [[ 5,  7,  9],
        [ 8, 10, 12]],

       [[ 8, 10, 12],
        [11, 13, 15]]])

array([[[ 0,  0,  0],
        [ 3,  3,  3]],

       [[-3, -3, -3],
        [ 0,  0,  0]],

       [[-6, -6, -6],
        [-3, -3, -3]]])

array([[[ 1,  4,  9],
        [ 4, 10, 18]],

       [[ 4, 10, 18],
        [16, 25, 36]],

       [[ 7, 16, 27],
        [28, 40, 54]]])

array([[[1.        , 1.        , 1.        ],
        [4.        , 2.5       , 2.        ]],

       [[0.25      , 0.4       , 0.5       ],
        [1.        , 1.        , 1.        ]],

       [[0.14285714, 0.25      , 0.33333333],
        [0.57142857, 0.625     , 0.66666667]]])

array([[[0, 0, 0],
        [0, 1, 0]],

       [[1, 2, 3],
        [0, 0, 0]],

       [[1, 2, 3],
        [4, 5, 6]]])

array([[[1, 1, 1],
        [4, 2, 2]],

       [[0, 0, 0],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0]]])

array([[[       1,        4,       27],
        [       4,       25,      216]],

       [[       1,       32,      729],
        [     256,     3125,    46656]],

       [[       1,      256,    19683],
        [   16384,   390625, 10077696]]])

#### 维度不同

In [20]:
a = np.arange(1,7).reshape(1,2,3)
b = np.arange(1,7).reshape(2,3)
display(a,b)

array([[[1, 2, 3],
        [4, 5, 6]]])

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
display(a + b, a - b, a * b, a / b, a%b, a//b, a**b)

array([[[ 2,  4,  6],
        [ 8, 10, 12]]])

array([[[0, 0, 0],
        [0, 0, 0]]])

array([[[ 1,  4,  9],
        [16, 25, 36]]])

array([[[1., 1., 1.],
        [1., 1., 1.]]])

array([[[0, 0, 0],
        [0, 0, 0]]])

array([[[1, 1, 1],
        [1, 1, 1]]])

array([[[    1,     4,    27],
        [  256,  3125, 46656]]])

In [22]:
a = np.arange(1,16).reshape(3,1,5)
b = np.arange(1,7).reshape(1,6)
display(a,b)

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]]])

array([[1, 2, 3, 4, 5, 6]])

In [23]:
display(a + b, a - b, a * b, a / b, a%b, a//b, a**b)

ValueError: operands could not be broadcast together with shapes (3,1,5) (1,6) 

In [24]:
a = np.arange(1,16).reshape(3,1,5)
b = np.arange(1,6).reshape(1,5)
display(a,b)

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]]])

array([[1, 2, 3, 4, 5]])

In [25]:
display(a + b, a - b, a * b, a / b, a%b, a//b, a**b)

array([[[ 2,  4,  6,  8, 10]],

       [[ 7,  9, 11, 13, 15]],

       [[12, 14, 16, 18, 20]]])

array([[[ 0,  0,  0,  0,  0]],

       [[ 5,  5,  5,  5,  5]],

       [[10, 10, 10, 10, 10]]])

array([[[ 1,  4,  9, 16, 25]],

       [[ 6, 14, 24, 36, 50]],

       [[11, 24, 39, 56, 75]]])

array([[[ 1.        ,  1.        ,  1.        ,  1.        ,
          1.        ]],

       [[ 6.        ,  3.5       ,  2.66666667,  2.25      ,
          2.        ]],

       [[11.        ,  6.        ,  4.33333333,  3.5       ,
          3.        ]]])

array([[[0, 0, 0, 0, 0]],

       [[0, 1, 2, 1, 0]],

       [[0, 0, 1, 2, 0]]])

array([[[ 1,  1,  1,  1,  1]],

       [[ 6,  3,  2,  2,  2]],

       [[11,  6,  4,  3,  3]]])

array([[[     1,      4,     27,    256,   3125]],

       [[     6,     49,    512,   6561, 100000]],

       [[    11,    144,   2197,  38416, 759375]]])

In [26]:
a = np.arange(1,5).reshape(1,2,1,2)
b = np.arange(1,21).reshape(2,5,2)
display(a,b)

array([[[[1, 2]],

        [[3, 4]]]])

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [27]:
display(a + b, a - b, a * b, a / b, a%b, a//b, a**b)

array([[[[ 2,  4],
         [ 4,  6],
         [ 6,  8],
         [ 8, 10],
         [10, 12]],

        [[14, 16],
         [16, 18],
         [18, 20],
         [20, 22],
         [22, 24]]]])

array([[[[  0,   0],
         [ -2,  -2],
         [ -4,  -4],
         [ -6,  -6],
         [ -8,  -8]],

        [[ -8,  -8],
         [-10, -10],
         [-12, -12],
         [-14, -14],
         [-16, -16]]]])

array([[[[ 1,  4],
         [ 3,  8],
         [ 5, 12],
         [ 7, 16],
         [ 9, 20]],

        [[33, 48],
         [39, 56],
         [45, 64],
         [51, 72],
         [57, 80]]]])

array([[[[1.        , 1.        ],
         [0.33333333, 0.5       ],
         [0.2       , 0.33333333],
         [0.14285714, 0.25      ],
         [0.11111111, 0.2       ]],

        [[0.27272727, 0.33333333],
         [0.23076923, 0.28571429],
         [0.2       , 0.25      ],
         [0.17647059, 0.22222222],
         [0.15789474, 0.2       ]]]])

array([[[[0, 0],
         [1, 2],
         [1, 2],
         [1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4],
         [3, 4],
         [3, 4],
         [3, 4]]]])

array([[[[1, 1],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]]])

array([[[[         1,          4],
         [         1,         16],
         [         1,         64],
         [         1,        256],
         [         1,       1024]],

        [[    177147,   16777216],
         [   1594323,  268435456],
         [  14348907,          0],
         [ 129140163,          0],
         [1162261467,          0]]]])

In [30]:
a = np.arange(1,7).reshape(1,2,3)
b = np.arange(1,4)
display(a,b)

array([[[1, 2, 3],
        [4, 5, 6]]])

array([1, 2, 3])

In [31]:
display(a + b, a - b, a * b, a / b, a%b, a//b, a**b)

array([[[2, 4, 6],
        [5, 7, 9]]])

array([[[0, 0, 0],
        [3, 3, 3]]])

array([[[ 1,  4,  9],
        [ 4, 10, 18]]])

array([[[1. , 1. , 1. ],
        [4. , 2.5, 2. ]]])

array([[[0, 0, 0],
        [0, 1, 0]]])

array([[[1, 1, 1],
        [4, 2, 2]]])

array([[[  1,   4,  27],
        [  4,  25, 216]]])

##### 一些判断方法
- np.isnan(数组)	判断数组中元素是否是空值（NaN）	返回：布尔数组
- np.isinf(数组)	判断数组中元素是否是无穷大或无穷小	返回：布尔数组
- np.isfinite(数组)	判断数组中元素是否是有限数值	返回：布尔数组
- np.floor(数组)	数组中元素向下取整，比元素小的最大整数	返回：数组
- np.ceil(数组)	数组中元素向上取整，比元素大的最小整数	返回：数组
- np.abs(数组)	数组中元素取绝对值	返回：数组
- np.square(数组)	数组中元素求平方	返回：数组

In [43]:
data = np.arange(10,dtype=np.float64).reshape(2,5)
data[0, 1] = np.nan
data

array([[ 0., nan,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

In [44]:
np.isnan(data)

array([[False,  True, False, False, False],
       [False, False, False, False, False]])

In [45]:
np.isinf(data)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

### np.where(条件, x, y)：数组中元素若满足条件，则值为x，否则值为y。返回：数组
- np.where(条件)：如果对象是一维数组，则返回满足条件元素的下标组成的一维数组
- np.where(条件)：如果对象是二维数组：
    - 则返回一个元组，元组的元素是数组，元组有两个元素，分别是满足条件的元素行索引组成的数组和列索引组成的数组
- np.where(条件)：如果对象是高维数组：以此类推
- np.where(条件, x, y)：则满足条件的元素，使用x进行替换，不满足的使用y进行替换
- 特别的： 设a是一个数组
    - np.where(条件, a, y) ：则满足条件的元素还保持不变，不满足的元素使用y替换
    - np.where(条件, x, a) ：则满足条件的元素使用x替换，不满足的元素还保持不变
- np.where(条件, x, y)：
    - 因为条件执行后是布尔数组，因此直接传递布尔数组也可以

In [50]:
data = np.arange(20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
np.where(data > 10)

(array([2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [48]:
np.where(data > 10, 100, 20)

array([[ 20,  20,  20,  20,  20],
       [ 20,  20,  20,  20,  20],
       [ 20, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [52]:
np.where(data > 10, data, 20)

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
np.where(data > 10, 100, data)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

#### 数组排序 
- np.sort()
- axis：指定轴，默认以最大轴排序 （0，1） 以1轴排序 (0,1,2) 以2轴排序

In [54]:
data = np.array([2,1,8,4,0,5,8,3])
display(data, np.sort(data))

array([2, 1, 8, 4, 0, 5, 8, 3])

array([0, 1, 2, 3, 4, 5, 8, 8])

In [55]:
data = np.array([[2,3,1,8,4,0],[6,1,6,3,9,8]])
display(data, np.sort(data))

array([[2, 3, 1, 8, 4, 0],
       [6, 1, 6, 3, 9, 8]])

array([[0, 1, 2, 3, 4, 8],
       [1, 3, 6, 6, 8, 9]])

In [57]:
data = np.array([[2,3,1,8,4,0],[6,1,6,3,9,8]])
display(data, np.sort(data, axis=1))

array([[2, 3, 1, 8, 4, 0],
       [6, 1, 6, 3, 9, 8]])

array([[0, 1, 2, 3, 4, 8],
       [1, 3, 6, 6, 8, 9]])