## numpy矩阵运算

In [1]:
import numpy as np

> numpy提供了大量的矩阵相关的计算方法

### 创建矩阵
- 1. numpy提供的二维数组array可以视为矩阵
- 2. 通过numpy.matrix()创建矩阵
- 3. 通过nump。mat()创建矩阵 （过于麻烦，省略）

In [3]:
matrix1 = np.arange(10,40).reshape(5,6)
matrix1

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [4]:
matrix2 = np.matrix(matrix1)
matrix2

matrix([[10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33],
        [34, 35, 36, 37, 38, 39]])

- 由于numpy的二维数组可以直接视为矩阵进行矩阵计算，所以通过数组创建矩阵更为常见

- 创建单位矩阵，方正，且主对角线元素为1，其余为0
    - numpy.eye()

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- 创建指定对角线元素的对角矩阵
    - numpy.diag()

In [57]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [58]:
np.diag(np.arange(7))

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6]])

### 矩阵运算

#### 1. 矩阵转置
- 使用array的属性T
- 使用numpy.transpose()方法

In [5]:
matrix = np.arange(10).reshape(2,5)
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
matrix.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [7]:
np.transpose(matrix)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### 2. 矩阵乘法
- 矩阵乘法：第一个矩阵维度 (m,k) 第二个为(k,n) 结果（m,n） 也就是第一个矩阵的列数要等于第二个矩阵的行数
- 使用 ndarray.dot(ndarray)
- 使用 numpy.dot(ndarray, ndarray)
- 使用 numpy.matmul(ndarray, ndarray)
- 使用 @ 运算符 ndarray@ndarray

In [9]:
matrix1 = np.arange(10).reshape(2,5)
matrix2 = np.arange(35).reshape(5,7)
display(matrix1, matrix2)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [10]:
matrix1.dot(matrix2)

array([[210, 220, 230, 240, 250, 260, 270],
       [560, 595, 630, 665, 700, 735, 770]])

In [11]:
np.dot(matrix1,matrix2)

array([[210, 220, 230, 240, 250, 260, 270],
       [560, 595, 630, 665, 700, 735, 770]])

In [17]:
np.matmul(matrix1,matrix2)

array([[210, 220, 230, 240, 250, 260, 270],
       [560, 595, 630, 665, 700, 735, 770]])

In [18]:
matrix1 @ matrix2

array([[210, 220, 230, 240, 250, 260, 270],
       [560, 595, 630, 665, 700, 735, 770]])

- 矩阵数乘：和矩阵里每个元素相乘

In [12]:
matrix1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
matrix1 * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

- 矩阵加法：对应位置元素相加

In [14]:
matrix1 + matrix1

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

- 矩阵减法法：对应位置元素相减

In [16]:
matrix1 - matrix1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

- 矩阵元素乘法，对应位置元素相乘（真正矩阵里没有这种运算，这里为了方便取了这个名字）
    - 使用 *
    - 使用 numpy.multiply(ndarray,ndarray)

In [19]:
matrix1 = np.arange(10).reshape(2,5)
matrix1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matrix1 * matrix1

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [21]:
np.multiply(matrix1,matrix1)

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

- 计算方正的迹：也就是方形矩阵的主对角线元素的和
    - numpy.trace()

In [24]:
matrix = np.arange(25).reshape(5,-1)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
np.trace(matrix)

60

### numpy还提供了numpy.linalg模块，用于计算矩阵、线性代数的计算

#### 1. 求逆矩阵
- 矩阵必须是方阵
- 矩阵可逆
- numpy.linalg.inv()

In [29]:
from numpy import linalg

In [33]:
matrix = np.arange(25).reshape(5,5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
linalg.inv(matrix)  # 不可逆

LinAlgError: Singular matrix

In [34]:
matrix = np.array([[1,2],[4,5]])
matrix

array([[1, 2],
       [4, 5]])

In [35]:
linalg.inv(matrix)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

#### 2. 计算行列式
- 只有方阵才有行列式
- numpy.linalg.det()

In [40]:
matrix = np.array([[1,2],[4,5]])
matrix

array([[1, 2],
       [4, 5]])

In [41]:
linalg.det(matrix)

-2.9999999999999996

#### 3. 计算特征值和特征向量
- linalg.eigvals() 特征值
- linalg.eig() 特征向量

In [42]:
linalg.eigvals(matrix)

array([-0.46410162,  6.46410162])

In [43]:
linalg.eig(matrix)

(array([-0.46410162,  6.46410162]),
 array([[-0.80689822, -0.34372377],
        [ 0.59069049, -0.9390708 ]]))

#### 4. 求解线性方程
> 1. x - 4*z = 0 
> 2. -2*x + 2*y + 5*z = 8
> 3. x - 8*y + 9*z = -9

求解：x,y,z
- 使用linalg.solve()方法

In [47]:
matrix = np.array([[1,0,-4],[-2,2,5],[1,-8,9]])
matrix

array([[ 1,  0, -4],
       [-2,  2,  5],
       [ 1, -8,  9]])

In [50]:
matrix_A = np.array([0,8,-9])
matrix_A

array([ 0,  8, -9])

In [51]:
linalg.solve(matrix, matrix_A)

array([92. , 38.5, 23. ])

#### 5. 矩阵奇异值分解
- linalg.svd()
- 对矩阵 A 进行奇异值分解 得到三个矩阵 S, V, D 其中V是对角矩阵 np.dot(np.dot(S,V),D)=A

In [52]:
matrix = np.arange(25).reshape(5,5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
S, V, D = linalg.svd(matrix)
display(S, V, D)

array([[-0.06767881, -0.77163436,  0.62387979, -0.10228113, -0.01767993],
       [-0.22699517, -0.49847085, -0.59633074,  0.17664114,  0.55963162],
       [-0.38631153, -0.22530735, -0.28489476,  0.35103754, -0.77175619],
       [-0.54562789,  0.04785615, -0.13673742, -0.82287399, -0.06466276],
       [-0.70494424,  0.32101965,  0.39408313,  0.39747644,  0.29446726]])

array([6.99085940e+01, 3.57609824e+00, 6.39273548e-15, 1.24087941e-15,
       2.39254844e-16])

array([[-0.39024378, -0.41787354, -0.4455033 , -0.47313306, -0.50076282],
       [ 0.66911119,  0.35409279,  0.03907438, -0.27594403, -0.59096243],
       [ 0.35081431,  0.06267898, -0.5839024 , -0.42348937,  0.59389848],
       [-0.22554577,  0.5517669 , -0.61603913,  0.4789606 , -0.18914261],
       [ 0.47545602, -0.62579919, -0.28205279,  0.53967907, -0.10728311]])

In [56]:
np.dot(np.dot(S,np.diag(V)),D)

array([[1.20372232e-15, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
        4.00000000e+00],
       [5.00000000e+00, 6.00000000e+00, 7.00000000e+00, 8.00000000e+00,
        9.00000000e+00],
       [1.00000000e+01, 1.10000000e+01, 1.20000000e+01, 1.30000000e+01,
        1.40000000e+01],
       [1.50000000e+01, 1.60000000e+01, 1.70000000e+01, 1.80000000e+01,
        1.90000000e+01],
       [2.00000000e+01, 2.10000000e+01, 2.20000000e+01, 2.30000000e+01,
        2.40000000e+01]])

#### 6. 广义逆矩阵
- linalg.pinv()

In [59]:
matrix = np.arange(25).reshape(5,5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
linalg.pinv(matrix)

array([[-1.44000000e-01, -9.20000000e-02, -4.00000000e-02,
         1.20000000e-02,  6.40000000e-02],
       [-7.60000000e-02, -4.80000000e-02, -2.00000000e-02,
         8.00000000e-03,  3.60000000e-02],
       [-8.00000000e-03, -4.00000000e-03, -7.80625564e-17,
         4.00000000e-03,  8.00000000e-03],
       [ 6.00000000e-02,  4.00000000e-02,  2.00000000e-02,
         1.30104261e-17, -2.00000000e-02],
       [ 1.28000000e-01,  8.40000000e-02,  4.00000000e-02,
        -4.00000000e-03, -4.80000000e-02]])