## numpy的随机数 和 随机数数组

In [1]:
import numpy as np

### 在numpy的random模块提供了随机数一系列操作

#### 1.随机整数
- randint(low, high=None, size=None, dtype=int)
- low：最小值 默认值为0
- high：最大值（产生的随机数不会包括最大值）左闭右开区间
- size：维度 是一个元组

In [8]:
np.random.randint(1)

0

In [16]:
np.random.randint(1,10)

8

In [17]:
np.random.randint(1,10, (2,3))

array([[4, 6, 1],
       [6, 1, 3]])

In [19]:
np.random.randint(1,10, (3,2,4))

array([[[7, 9, 4, 3],
        [9, 9, 7, 2]],

       [[9, 6, 1, 7],
        [5, 8, 6, 6]],

       [[4, 3, 9, 6],
        [2, 8, 9, 2]]])

#### 2. 符合均匀分布的随机小数
- rand(d0, d1, ..., dn)
- rand() 符合均匀分布的一个随机小数
- 只需要传入维度即可，可以传入多个整数,表示多个维度，注意这里不能传入元组

In [20]:
np.random.rand()

0.974969283352626

In [21]:
np.random.rand(2,3)

array([[0.36291249, 0.05769132, 0.22175987],
       [0.37923222, 0.40011696, 0.88195271]])

In [22]:
np.random.rand((2,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [24]:
np.random.rand(2,3,4)

array([[[0.47798648, 0.16795227, 0.71250803, 0.38070688],
        [0.20060794, 0.20551884, 0.67035765, 0.9941468 ],
        [0.42551237, 0.06836194, 0.8870949 , 0.3591658 ]],

       [[0.39221637, 0.25526215, 0.15342555, 0.43006436],
        [0.70564218, 0.48413537, 0.61502808, 0.98996331],
        [0.72418645, 0.15373721, 0.94641195, 0.49128386]]])

#### 3. 符合标准正太分布的随机小数（均值为0，方差为1）
- randn(d0, d1, ..., dn)
- randn() 符合标准正太分布的一个随机小数
- 只需要传入维度即可，可以传入多个整数,表示多个维度，注意这里不能传入元组

In [26]:
np.random.randn()

-1.3457572949388712

In [27]:
np.random.randn(2,3)

array([[-0.97744159, -0.52320055, -0.31242089],
       [ 0.0637586 , -0.16311528, -0.70036197]])

In [28]:
np.random.randn(2,3,4)

array([[[ 1.17317535, -0.46921922, -0.40292827,  1.74193227],
        [ 1.60906897, -0.7598998 , -1.03801223,  0.36999972],
        [-1.65716509,  0.87413897, -1.22197772,  0.23222278]],

       [[-0.31772856, -0.21108696, -0.95136798, -0.3260545 ],
        [-0.91915784,  0.15181436, -0.51520062, -0.42896316],
        [-0.00353637, -1.02281419,  0.96519864, -0.35881445]]])

#### 4. 符合正太分布的随机小数（均值和方差需要传入）
- normal(loc=0.0, scale=1.0, size=None)
- loc：均值
- scale ：方差
- normal默认是标准正太分布
- randn() 符合标准正太分布的一个随机小数
- size：传入元组表示维度

In [30]:
np.random.normal()

-0.5348694305948958

In [31]:
np.random.normal(2, 4)

3.688010701698519

In [33]:
np.random.normal(size=(3,4))

array([[ 0.90563062, -2.72085542, -0.266634  ,  1.29744644],
       [-0.50721192,  0.5093526 , -0.12635508, -1.83985823],
       [-0.55974308,  0.10364342, -0.4874388 ,  0.1755633 ]])

In [34]:
np.random.normal(1, 2, size=(2, 3,4))

array([[[ 2.77022901,  2.94628114,  4.89616963,  1.18852988],
        [ 3.94467558, -0.19912988, -0.7510624 ,  0.9917585 ],
        [ 1.55112359,  1.71840587,  1.91535287,  1.63519916]],

       [[ 3.36630953,  0.25735797,  2.99091576,  2.61015618],
        [ 2.3056878 ,  2.07259595,  1.76325742,  2.64154274],
        [-2.25095138,  0.53904199,  0.05878357,  1.49243096]]])

#### 5. 生成0~1之间的随机小数
- random(size=None)  左闭右开区间 [0,1)
- size：传入元组表示维度

In [35]:
np.random.random()

0.7655605197302492

In [37]:
np.random.random((2,3))

array([[0.67244657, 0.68182581, 0.48312288],
       [0.32146098, 0.38984176, 0.25742743]])

In [38]:
np.random.random((2,3,4))

array([[[0.96039107, 0.17659401, 0.19683013, 0.68451833],
        [0.50651515, 0.30970798, 0.05665532, 0.39166964],
        [0.40122881, 0.86383783, 0.50683867, 0.70122881]],

       [[0.39048292, 0.83563202, 0.87752641, 0.76305009],
        [0.110547  , 0.68401315, 0.63588462, 0.10222048],
        [0.89978415, 0.33350306, 0.62715411, 0.04814283]]])

#### 6. 产生给定区间的数组，并且打乱顺序
- permutation(x)
- x：表示最大值
- permutation(x)：生成从0到x的不包括x的x个数，并且乱序

In [45]:
np.random.permutation(10)

array([6, 2, 8, 7, 9, 5, 0, 1, 4, 3])

In [46]:
np.random.permutation(20)

array([16, 18,  8, 13,  4,  5, 14, 17,  6, 10,  2,  7,  1,  0, 12, 15,  9,
       19, 11,  3])

#### 7. 将有序数组打乱
- shuffle(x)
- x：数组、列表，高纬度也可

In [48]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.random.shuffle(data)
data

array([8, 6, 0, 2, 7, 9, 4, 3, 1, 5])

In [52]:
data_list = [i for i in range(15)]

In [53]:
np.random.shuffle(data_list)
data_list

[10, 2, 11, 14, 3, 9, 7, 6, 13, 0, 12, 5, 1, 4, 8]

In [55]:
data = np.arange(20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
np.random.shuffle(data)
data

array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

#### 8. 随机种子，
- seed(seed=None)
- seed ： 给定seed后，在随机种子下面的，每个随机函数产生的随机数据都不会被改变
- 最好将seed(seed=None)设置在最前面