## numpy数组的增删改

In [2]:
import numpy as np

- numpy.append() 在数组末尾添加数据
- numpy.insert() 在数组指定位置添加数据

#### 一位数组
- numpy.append() 生成新的数组副本
- 可以添加：
    - 单个元素
    - 列表
    - 元组
    - 数组
- append()会将序列拆开一个个添加到数组末尾

In [3]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [4]:
np.append(data, 10)

array([ 1,  2,  3,  4,  5, 10])

In [5]:
np.append(data, [100, 200])

array([  1,   2,   3,   4,   5, 100, 200])

In [7]:
np.append(data, (100, 200))

array([  1,   2,   3,   4,   5, 100, 200])

In [8]:
np.append(data, np.arange(5))

array([1, 2, 3, 4, 5, 0, 1, 2, 3, 4])

- numpy.insert() 生成新的数组副本
- insert(arr, obj, values)
    - arr 原始数组
    - 需要添加的下标
    - 添加的值
- 可以添加：
    - 单个元素
    - 列表
    - 元组
    - 数组
- insert()会将序列拆开一个个添加到数组末尾

In [9]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [11]:
np.insert(data, 0, 100)

array([100,   1,   2,   3,   4,   5])

In [12]:
np.insert(data, 1, [100, 200])

array([  1, 100, 200,   2,   3,   4,   5])

In [13]:
np.insert(data, 2, (100, 200))

array([  1,   2, 100, 200,   3,   4,   5])

In [14]:
np.insert(data, 3, np.arange(5))

array([1, 2, 3, 0, 1, 2, 3, 4, 4, 5])

#### 二维数组
> 二维数组添加和一维数组不同，因为二维数组有两个轴，可以指定轴添加元素

- numpy.append() 

In [16]:
data = np.arange(20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

- 不指定轴情况
> 不指定轴的情况，append会先把数组展开为一维数组，然后按照一维数组添加元素的方法添加

In [17]:
np.append(data, 100)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 100])

In [18]:
np.append(data, [100, 200])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 100, 200])

- 指定0轴，也就是行
- 在append()方法里传入形参 axis=0
- 注意：二维数组，0轴代表行，所以使用append添加元素，是添加行
- 要添加和原始行相同长度的：
    - 二维列表
    - 二维数组

In [74]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
np.append(data, [[num for num in range(100,600,100)]], axis=0)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [100, 200, 300, 400, 500]])

In [26]:
index = np.arange(5).reshape(1,-1)
index

array([[0, 1, 2, 3, 4]])

In [27]:
np.append(data, index, axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4]])

- 当然也可以一次增加多行，只要保证和原数组维度相同，且行的元素长度相同

In [30]:
new_data = np.arange(10).reshape(-1,5)
new_data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
np.append(data, new_data, axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

- 指定1轴，也就是列
- 在append()方法里传入形参 axis=1
- 注意：二维数组，1轴代表列，所以使用append添加元素，是添加列
- 要添加和原始列相同长度的：
    - 二维列表
    - 二维数组

In [32]:
data = np.arange(20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
np.append(data, [[num] for num in range(100,500,100)], axis=1)

array([[  0,   1,   2,   3,   4, 100],
       [  5,   6,   7,   8,   9, 200],
       [ 10,  11,  12,  13,  14, 300],
       [ 15,  16,  17,  18,  19, 400]])

In [36]:
column_list = [[10], [20], [30], [40]]
column_list

[[10], [20], [30], [40]]

In [37]:
np.append(data, column_list, axis=1)

array([[ 0,  1,  2,  3,  4, 10],
       [ 5,  6,  7,  8,  9, 20],
       [10, 11, 12, 13, 14, 30],
       [15, 16, 17, 18, 19, 40]])

In [40]:
column = np.arange(4).reshape(-1,1)
column

array([[0],
       [1],
       [2],
       [3]])

In [41]:
np.append(data, column, axis=1)

array([[ 0,  1,  2,  3,  4,  0],
       [ 5,  6,  7,  8,  9,  1],
       [10, 11, 12, 13, 14,  2],
       [15, 16, 17, 18, 19,  3]])

- 增加多列

In [44]:
multi_column = np.arange(20).reshape(-1,5)
multi_column

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
np.append(data, multi_column, axis=1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

- numpy.insert()
- numpy.insert()和append()方法使用规则同理，只不过numpy.insert()可以指定任意位置添加数据

In [98]:
data = np.arange(20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

- 不指定轴情况，默认展开为一维数组添加

In [47]:
np.insert(data, 0, 100)

array([100,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19])

In [48]:
np.insert(data, 1, [100, 200])

array([  0, 100, 200,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
        11,  12,  13,  14,  15,  16,  17,  18,  19])

- 指定0轴，也就是行
- 在insert()方法里传入形参 axis=0
- 注意：二维数组，0轴代表行，所以使用insert添加元素，是添加行
- 要添加和原始行相同长度的：
    - 二维列表
    - 二维数组
    - 一维列表
    - 一维数组
    - 标量 （标量会扩展成一维数组，再添加）

In [102]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [103]:
np.insert(data, 0, 1, axis=0)

array([[ 1,  1,  1,  1,  1],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [101]:
np.insert(data, 0, [[num for num in range(100,600,100)]], axis=0)

array([[100, 200, 300, 400, 500],
       [  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [104]:
np.insert(data, 0, [num for num in range(100,600,100)], axis=0)

array([[100, 200, 300, 400, 500],
       [  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [105]:
index = np.arange(5).reshape(1,-1)
index

array([[0, 1, 2, 3, 4]])

In [106]:
np.insert(data, 3, index, axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [107]:
index = np.arange(5)
index

array([0, 1, 2, 3, 4])

In [108]:
np.insert(data, 3, index, axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

- 当然也可以一次增加多行，只要保证和原数组维度相同，且行的元素长度相同

In [53]:
new_data = np.arange(10).reshape(-1,5)
new_data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
np.insert(data, 1, new_data, axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

- 指定1轴，也就是列
- 在insert()方法里传入形参 axis=1
- 注意：二维数组，1轴代表列，所以使用insert添加元素，是添加列
- 要添加和原始列相同长度的：
    1. 若使用一维数组作为值添加，则插入位置 使用标量obj
    2. 若使用二维数组作为值添加，则插入位置 使用列表[obj]
    3. 也可以使用标量

In [109]:
data = np.arange(20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [110]:
np.insert(data, 1, 100, axis=1)

array([[  0, 100,   1,   2,   3,   4],
       [  5, 100,   6,   7,   8,   9],
       [ 10, 100,  11,  12,  13,  14],
       [ 15, 100,  16,  17,  18,  19]])

In [113]:
np.insert(data, 1, [num for num in range(100,500,100)], axis=1)

array([[  0, 100,   1,   2,   3,   4],
       [  5, 200,   6,   7,   8,   9],
       [ 10, 300,  11,  12,  13,  14],
       [ 15, 400,  16,  17,  18,  19]])

In [84]:
np.insert(data, [1], [[num] for num in range(100,500,100)], axis=1)

array([[  0, 100,   1,   2,   3,   4],
       [  5, 200,   6,   7,   8,   9],
       [ 10, 300,  11,  12,  13,  14],
       [ 15, 400,  16,  17,  18,  19]])

In [85]:
column_list = [10, 20, 30, 40]
column_list

[10, 20, 30, 40]

In [86]:
np.insert(data, 1, column_list, axis=1)

array([[ 0, 10,  1,  2,  3,  4],
       [ 5, 20,  6,  7,  8,  9],
       [10, 30, 11, 12, 13, 14],
       [15, 40, 16, 17, 18, 19]])

In [87]:
column_list = [[10], [20], [30],[40]]
column_list

[[10], [20], [30], [40]]

In [88]:
np.insert(data, [1], column_list, axis=1)

array([[ 0, 10,  1,  2,  3,  4],
       [ 5, 20,  6,  7,  8,  9],
       [10, 30, 11, 12, 13, 14],
       [15, 40, 16, 17, 18, 19]])

In [89]:
column = np.arange(4).reshape(4,-1)
column

array([[0],
       [1],
       [2],
       [3]])

In [90]:
np.insert(data, [0], column, axis=1)

array([[ 0,  0,  1,  2,  3,  4],
       [ 1,  5,  6,  7,  8,  9],
       [ 2, 10, 11, 12, 13, 14],
       [ 3, 15, 16, 17, 18, 19]])

- 增加多列

In [66]:
multi_column = np.arange(20).reshape(-1,5)
multi_column

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [91]:
np.insert(data, [4], multi_column, axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  9,  9],
       [10, 11, 12, 13, 10, 11, 12, 13, 14, 14],
       [15, 16, 17, 18, 15, 16, 17, 18, 19, 19]])

### 注意：
- 二维情况下指定轴进行插入操作
    - 使用insert()方法
        - 指定行插入，需要插入二维数组或者二维列表
        - 指定列插入，可以插入一维数组或者一维列表，不过此时插入的位置必须是标量 obj
        - 指定列插入，也可以插入二维数组或者二维列表，不过此时插入的位置必须是列表 [obj]

- 使用insert()方法，指定行轴，其插入位置可以是标量obj也可以是列表，表示在多个位置插入

In [92]:
data = np.insert(data, [4], multi_column, axis=1)
data

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  9,  9],
       [10, 11, 12, 13, 10, 11, 12, 13, 14, 14],
       [15, 16, 17, 18, 15, 16, 17, 18, 19, 19]])

In [93]:
new_data = np.ones((1,10))
new_data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [94]:
np.insert(data, [0,3,4], new_data, axis=0)

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 0,  1,  2,  3,  0,  1,  2,  3,  4,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  9,  9],
       [10, 11, 12, 13, 10, 11, 12, 13, 14, 14],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [15, 16, 17, 18, 15, 16, 17, 18, 19, 19],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [96]:
new_data = np.ones(10)
np.insert(data, 0, new_data, axis=0)

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 0,  1,  2,  3,  0,  1,  2,  3,  4,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  9,  9],
       [10, 11, 12, 13, 10, 11, 12, 13, 14, 14],
       [15, 16, 17, 18, 15, 16, 17, 18, 19, 19]])

## 总结：
- append()：是在尾部增加数据
- insert()：可以在指定位置增加数据
- 一维数组情况下增加数据
    - append()可以在尾部增加一个或者多个变量组成数组、列表、元组等
    - insert()可以在指定位置obj增加一个或者多个变量组成数组、列表、元组等
    - insert()可以在指定位置obj，其中obj是一个下标列表，则一次在多个地方增加元素，但是增加的元素必须是一个值，即不能增加数组、列表、元组
- 二维数组情况下增加数据
    - 不指定维度：append和insert都会将二维数组，转换成一维数组，再按照一维数组的规则添加数据
    - append()指定行或者列轴：
        - 不可以增加标量
        - 不可以增加一维数组或者列表
        - 可以增加单行或者列二维数组或者列表
        - 可以增加多行或者列的二维数组或者列表
    - insert()指定行或者列：
        - 可以增加标量                （行列均可）
        - 可以增加一维数组或者列表     （行列均可）
        - 可以增加单行二维数组或者列表  （行列均可,不过增加列需要使用列表下标[obj]）
        - 可以增加多行二维数组或者列表   （行列均可，不过增加列需要使用列表下标[obj]）
        - 可以一次增加多个位置：
            - 增加行或者列（标量）[obj1,obj2,...]
            - 增加行或者列（一维）[obj1,obj2,...]
            - 增加行或者列（二维多行多列）[obj1,obj2,...]
            - 增加行（二维单行单列）[obj1,obj2,...]
            - 增加列 <b>报错</b>（二维单行单列）[obj1,obj2,...]
            