## numpy索引和切片

In [2]:
import numpy as np

### numpy索引
> 根据下标取numpy数组中的元素
- 数组和列表相同，可以通过下标进行获取元素，并且使用规则相同

#### 一维数组
- 数组名[索引值]

In [3]:
data = np.array([i for i in range(20) if i % 2 == 0])
data

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
data[0]

0

In [5]:
data[6]

12

#### 二维数组
- 二维数组相当于是一维数组，但是此一维数组的元素又是一维数组
- 数组名[索引值]  ：此种方式取出的是一个一维数组
- 数组名[索引值][索引值] ：此种方式取出的是二维数组中的一个元素
- 数组名[行索引,列索引] ：此种方式可以直接获得二维数组的某个元素

In [6]:
data = np.arange(20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
data[3]

array([15, 16, 17, 18, 19])

In [8]:
data[0]

array([0, 1, 2, 3, 4])

In [9]:
data[3][2]

17

In [10]:
data[3,2]

17

三维数组
- 三维数组可以看作是一个一维数组，不过这个一维数组的元素是二维数组
- 取元素方式和二维数组相同，只不过多一个维度

In [11]:
data = np.arange(20).reshape(2,2,5)
data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [12]:
data[0]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
data[1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
data[0][1]

array([5, 6, 7, 8, 9])

In [14]:
data[0,1]

array([5, 6, 7, 8, 9])

In [18]:
data[1][0]

array([10, 11, 12, 13, 14])

In [16]:
data[1,0]

array([10, 11, 12, 13, 14])

In [19]:
data[0][0][0]

0

In [20]:
data[0,0,0]

0

In [21]:
data[1][1][3]

18

In [22]:
data[1,1,3]

18

- 高维数组同理
- 一维数组取出的是一个元素
- 二维数组取出的是一个一维数组
- 三维数组取出的是一个二维数组
- n维数组取出的是一个n-1维数组

### numpy切片
- numpy索引是取出一个元素，而切片是为了一次取出多个元素
- numpy数组的切片和list列表的切片使用规则基本相同 
- 数组名[start:end:step]  左闭右开区间
    1. start开始位置，默认为0
    2. end结束位置，默认为数组长度-1
    3. step步长，默认值为1
- 切片整个数组  数组名[::]
- 切片整个数组，且倒序  数组名[::-1.]

#### 一维数组

In [23]:
data = np.arange(15)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
data[1:5]

array([1, 2, 3, 4])

In [25]:
data[1:5:1]

array([1, 2, 3, 4])

In [26]:
data[1:10:2]

array([1, 3, 5, 7, 9])

In [27]:
data[-1:-10:-2]

array([14, 12, 10,  8,  6])

In [29]:
data[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
data[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 二维数组
- 二维数组分为行索引切片和列索引切片
- 二维数组名[行切片,列切片]
- 行切片或者列切片规则和一维数组切片规则相同
- 数组名[:,:] 表示原样切片
- 数组名[:,列切片] 表示保留所有行，再对列进行切片
- 数组名[行切片,:] 表示保留所有列，再对行进行切片

In [39]:
data = np.arange(20).reshape(4,-1)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
data[1]

array([5, 6, 7, 8, 9])

In [33]:
data[0:2,1:3]

array([[1, 2],
       [6, 7]])

In [34]:
data[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [35]:
data[0:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 三维数组切片
- 和二维数组切片类似，只是多了一个维度

In [41]:
data = np.arange(60).reshape(3,4,-1)
data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [42]:
data[1]

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [43]:
data[:,1:3,2:4]

array([[[ 7,  8],
        [12, 13]],

       [[27, 28],
        [32, 33]],

       [[47, 48],
        [52, 53]]])

In [44]:
data[:2,1:3,2:4]

array([[[ 7,  8],
        [12, 13]],

       [[27, 28],
        [32, 33]]])

### 不连续取值
- 一般来说，索引是取单个元素
- 切片是取多个连续元素
- 切片也可以取多个不连续元素
- 只要指定要取得元素位置即可

#### 一维数组
- 数组名[索引组成的列表或者数组]

In [45]:
data = np.array([1,3,6,0,4,8,2,5])
data

array([1, 3, 6, 0, 4, 8, 2, 5])

In [46]:
data[[0,4,1,2]]

array([1, 4, 3, 6])

In [47]:
index = np.array([0,4,1,2])
data[index]

array([1, 4, 3, 6])

#### 二维数组
- 数组名[行索引组成的列表或者数组, 列索引组成的列表或者数组]

In [49]:
data = np.arange(30).reshape(6,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [50]:
index = [1,3,5]
column = [0,1,4]
data[index,column]

array([ 5, 16, 29])

In [51]:
data[:,column]

array([[ 0,  1,  4],
       [ 5,  6,  9],
       [10, 11, 14],
       [15, 16, 19],
       [20, 21, 24],
       [25, 26, 29]])

In [52]:
data[index,:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

#### 三维数组同理

In [54]:
data = np.arange(60).reshape(-1,3,5)
data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [55]:
data[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
data[:,:,[1,3]]

array([[[ 1,  3],
        [ 6,  8],
        [11, 13]],

       [[16, 18],
        [21, 23],
        [26, 28]],

       [[31, 33],
        [36, 38],
        [41, 43]],

       [[46, 48],
        [51, 53],
        [56, 58]]])

In [58]:
data[[0,2],:,[1,3]]

array([[ 1,  6, 11],
       [33, 38, 43]])

In [60]:
data[[0,2],[1,2],[1,3]]

array([ 6, 43])

### 补充：布尔索引
- numpy数组可以使用布尔索引
- 当布尔索引的值为True时，才会取出对应元素
- 注意：直接使用布尔索引，需要将布尔索引组成的列表或者数组长度与要进行索引的数组长度相等

In [61]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
bool_index = [False,False,False,True,True,True,False,False,False,True]
data[bool_index]

array([3, 4, 5, 9])

- 布尔索引一般用于筛选数据
- 数组做逻辑运算会返回一个布尔数组
- 例如：筛选出数组中所有大于10的元素

In [64]:
data = np.arange(4,20)
data

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [65]:
data > 10

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [66]:
data[data>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [67]:
data = np.array([[1,3,5,7],[2,10,11,6],[4,10,21,0]])
data

array([[ 1,  3,  5,  7],
       [ 2, 10, 11,  6],
       [ 4, 10, 21,  0]])

In [68]:
data[data<9]

array([1, 3, 5, 7, 2, 6, 4, 0])

In [69]:
data[data==10]

array([10, 10])