# Array的属性

1. ndarray.shape	数组的形状，返回元组
2. ndarray.ndim	维度
3. ndarray.size	数组中元素的个数
4. ndarray.itemsize	数组中元素占用的长度（字节为单位）
5. ndarray.dtype 查看数组元素类型
6. ndarray.T  和矩阵的转置相同，也就是将原数组，行转成列

In [1]:
import numpy as np

- shape属性 shape会输出每个维度元素的个数，返回值是一个元组，元组长度就是数组的维度

In [2]:
data1 = np.arange(100, 120)
data1.shape

(20,)

In [3]:
data2 = data1.reshape(4,5)
data2.shape

(4, 5)

In [4]:
data3 = data2.reshape(2,2,5)
data3.shape

(2, 2, 5)

- ndim维度 这个属性直接输出数组的维度

In [5]:
data1.ndim

1

In [6]:
data2.ndim

2

In [7]:
data3.ndim

3

- size 元素个数  返回数组元素的总个数，也等同于shape属性中每个元素的乘积

In [8]:
data1.size

20

In [9]:
data2.size

20

In [10]:
data3.size

20

- itemsize 输出数组中元素占用的字节数

In [11]:
data1.itemsize

4

In [12]:
new_data = np.array([1,2,3],dtype=np.int8)
new_data.itemsize

1

In [13]:
new_data = np.array([1,2,3],dtype=np.int16)
new_data.itemsize

2

In [14]:
new_data = np.array([1,2,3],dtype=np.int32)
new_data.itemsize

4

In [15]:
new_data = np.array([1,2,3],dtype=np.int64)
new_data.itemsize

8

In [16]:
new_data = np.array([1,2,3],dtype=np.float16)
new_data.itemsize

2

In [17]:
new_data = np.array([1,2,3],dtype=np.float32)
new_data.itemsize

4

In [18]:
new_data = np.array([1,2,3],dtype=np.float64)
new_data.itemsize

8

- dtype  查看元素类型

In [19]:
data = np.arange(10, dtype=np.int16)
data.dtype

dtype('int16')

In [20]:
data = np.arange(10, dtype=np.int32)
data.dtype

dtype('int32')

In [21]:
data = np.arange(10, dtype=np.float16)
data.dtype

dtype('float16')

In [22]:
data = np.arange(10, dtype=np.float64)
data.dtype

dtype('float64')

- T 转置  对一维数组不起作用

In [24]:
data = np.arange(10, dtype=np.int16)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [25]:
data.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [26]:
data = np.arange(10, dtype=np.int16).reshape(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int16)

In [27]:
data.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]], dtype=int16)

In [28]:
data = np.arange(20, dtype=np.int16).reshape(2,2,5)
data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]], dtype=int16)

In [29]:
data.T

array([[[ 0, 10],
        [ 5, 15]],

       [[ 1, 11],
        [ 6, 16]],

       [[ 2, 12],
        [ 7, 17]],

       [[ 3, 13],
        [ 8, 18]],

       [[ 4, 14],
        [ 9, 19]]], dtype=int16)

## 注意：一维数组和一行的二维数组区别
> - 一维数组是没有行这个概念的
> - 只有多维数组才有行概念
> - 因此 np.arange(10) 和 np.arange(10).reshape(1,10) 有着本质的区别
> - 另外当修改一个数组的维度时候，使用reshape函数，可以将其中任意一个维度设置为-1，numpy会根据元素个数自动计算这个维度的值

In [31]:
data1 = np.arange(10)
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
data1.shape

(10,)

In [34]:
data.ndim

3

In [35]:
data2 = np.arange(10).reshape(1,10)
data2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
data2.shape

(1, 10)

In [37]:
data2.ndim

2

In [38]:
data3 = np.arange(100)
data3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
data4 = data3.reshape(10,-1)
data4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
data5 = data3.reshape(2,-1,10)
data5

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])